[tool.poetry]
name = "washington-high-lakes"
version = "0.1.0"
description = ""
authors = ["lp"]

[tool.poetry.dependencies]
python = ">=3.6,<4"
Flask = "^2.0.1"
whitenoise = "^5.3.0"
gunicorn = "^20.1.0"
